# [INFO] The latest environment for October 2025:
# https://docs.travis-ci.com/user/reference/linux#overview
dist: noble

git:
  depth: 1

language: node_js

# [INFO] Use the latest stable Node.js release:
# https://docs.travis-ci.com/user/languages/javascript-with-nodejs/#specifying-nodejs-versions
node_js:
- node

os: linux

script: skip
